databases:
  - name: contactdb
    databaseName: contactdb_5bns
    user: contactuser
    plan: free

services:
  - type: web
    name: contact-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: contactdb
          property: host
      - key: DB_PORT
        fromDatabase:
          name: contactdb
          property: port
      - key: DB_NAME
        fromDatabase:
          name: contactdb
          property: database
      - key: DB_USER
        fromDatabase:
          name: contactdb
          property: user
      - key: DB_PASS
        fromDatabase:
          name: contactdb
          property: password